import { ref } from 'vue'

// 卡片图片
export const cardImages = [
  { key: 'card_pack_poem', src: new URL('../../assets/cards/诗意卡包(2).png', import.meta.url).href },
  { key: 'card_pack_poet', src: new URL('../../assets/cards/诗人卡包(1).png', import.meta.url).href },
  { key: 'card_worker', src: new URL('../../assets/cards/书生.png', import.meta.url).href },
  { key: 'factory', src: new URL('../../assets/cards/工厂/书斋.png', import.meta.url).href },
  { key: 'unknown_card', src: new URL('../../assets/cards/未知卡片.png', import.meta.url).href },

  { key: 'love', src: new URL('../../assets/cards/诗意/爱情.png', import.meta.url).href },
  { key: 'sad', src: new URL('../../assets/cards/诗意/悲.png', import.meta.url).href },
  { key: 'spring', src: new URL('../../assets/cards/诗意/春.png', import.meta.url).href },
  { key: 'danbo', src: new URL('../../assets/cards/诗意/淡泊.png', import.meta.url).href },
  { key: 'home', src: new URL('../../assets/cards/诗意/故乡.png', import.meta.url).href },
  { key: 'yellowriver', src: new URL('../../assets/cards/诗意/黄河.png', import.meta.url).href },
  { key: 'fire', src: new URL('../../assets/cards/诗意/火.png', import.meta.url).href },
  { key: 'wine', src: new URL('../../assets/cards/诗意/酒.png', import.meta.url).href },
  { key: 'byebye', src: new URL('../../assets/cards/诗意/离别.png', import.meta.url).href },
  { key: 'liu', src: new URL('../../assets/cards/诗意/柳.png', import.meta.url).href },
  { key: 'bird', src: new URL('../../assets/cards/诗意/鸟.png', import.meta.url).href },
  { key: 'autumn', src: new URL('../../assets/cards/诗意/秋.png', import.meta.url).href },
  { key: 'sun', src: new URL('../../assets/cards/诗意/日.png', import.meta.url).href },
  { key: 'mountain', src: new URL('../../assets/cards/诗意/山.png', import.meta.url).href },
  { key: 'water', src: new URL('../../assets/cards/诗意/水.png', import.meta.url).href },
  { key: 'missing', src: new URL('../../assets/cards/诗意/思念.png', import.meta.url).href },
  { key: 'flower', src: new URL('../../assets/cards/诗意/桃花.png', import.meta.url).href },
  { key: 'goose', src: new URL('../../assets/cards/诗意/雁.png', import.meta.url).href },
  { key: 'friend', src: new URL('../../assets/cards/诗意/友情.png', import.meta.url).href },
  { key: 'rain', src: new URL('../../assets/cards/诗意/雨.png', import.meta.url).href },
  { key: 'moon', src: new URL('../../assets/cards/诗意/月.png', import.meta.url).href },
  { key: 'war', src: new URL('../../assets/cards/诗意/战争.png', import.meta.url).href },
  { key: 'longriver', src: new URL('../../assets/cards/诗意/长江.png', import.meta.url).href },
  { key: 'bamboo', src: new URL('../../assets/cards/诗意/竹.png', import.meta.url).href },
  { key: 'zhuangzhinanchou', src: new URL('../../assets/cards/诗意/壮志难酬.png', import.meta.url).href },
  { key: 'nature', src: new URL('../../assets/cards/诗意/自然.png', import.meta.url).href },

  { key: 'baijuyi', src: new URL('../../assets/cards/诗人/白居易.png', import.meta.url).href },
  { key: 'dufu', src: new URL('../../assets/cards/诗人/杜甫.png', import.meta.url).href },
  { key: 'libai', src: new URL('../../assets/cards/诗人/李白.png', import.meta.url).href },
  { key: 'lishangyin', src: new URL('../../assets/cards/诗人/李商隐.png', import.meta.url).href },
  { key: 'liuyuxi', src: new URL('../../assets/cards/诗人/刘禹锡.png', import.meta.url).href },
  { key: 'luyou', src: new URL('../../assets/cards/诗人/陆游.png', import.meta.url).href },
  { key: 'sushi', src: new URL('../../assets/cards/诗人/苏轼.png', import.meta.url).href },
  { key: 'taoyuanming', src: new URL('../../assets/cards/诗人/陶渊明.png', import.meta.url).href },
  { key: 'wanganshi', src: new URL('../../assets/cards/诗人/王安石.png', import.meta.url).href },
  { key: 'wangwei', src: new URL('../../assets/cards/诗人/王维.png', import.meta.url).href },
  { key: 'xinqiji', src: new URL('../../assets/cards/诗人/辛弃疾.png', import.meta.url).href },
  { key: 'yanshu', src: new URL('../../assets/cards/诗人/晏殊.png', import.meta.url).href },

  { key: 'factory_love', src: new URL('../../assets/cards/工厂/爱情.png', import.meta.url).href },
  { key: 'factory_sad', src: new URL('../../assets/cards/工厂/悲.png', import.meta.url).href },
  { key: 'factory_spring', src: new URL('../../assets/cards/工厂/春.png', import.meta.url).href },
  { key: 'factory_danbo', src: new URL('../../assets/cards/工厂/淡泊.png', import.meta.url).href },
  { key: 'factory_home', src: new URL('../../assets/cards/工厂/故乡.png', import.meta.url).href },
  { key: 'factory_yellowriver', src: new URL('../../assets/cards/工厂/黄河.png', import.meta.url).href },
  { key: 'factory_fire', src: new URL('../../assets/cards/工厂/火.png', import.meta.url).href },
  { key: 'factory_wine', src: new URL('../../assets/cards/工厂/酒.png', import.meta.url).href },
  { key: 'factory_byebye', src: new URL('../../assets/cards/工厂/离别.png', import.meta.url).href },
  { key: 'factory_liu', src: new URL('../../assets/cards/工厂/柳.png', import.meta.url).href },
  { key: 'factory_bird', src: new URL('../../assets/cards/工厂/鸟.png', import.meta.url).href },
  { key: 'factory_autumn', src: new URL('../../assets/cards/工厂/秋.png', import.meta.url).href },
  { key: 'factory_sun', src: new URL('../../assets/cards/工厂/日.png', import.meta.url).href },
  { key: 'factory_mountain', src: new URL('../../assets/cards/工厂/山.png', import.meta.url).href },
  { key: 'factory_water', src: new URL('../../assets/cards/工厂/水.png', import.meta.url).href },
  { key: 'factory_missing', src: new URL('../../assets/cards/工厂/思念.png', import.meta.url).href },
  { key: 'factory_flower', src: new URL('../../assets/cards/工厂/桃花.png', import.meta.url).href },
  { key: 'factory_goose', src: new URL('../../assets/cards/工厂/雁.png', import.meta.url).href },
  { key: 'factory_friend', src: new URL('../../assets/cards/工厂/友情.png', import.meta.url).href },
  { key: 'factory_rain', src: new URL('../../assets/cards/工厂/雨.png', import.meta.url).href },
  { key: 'factory_moon', src: new URL('../../assets/cards/工厂/月.png', import.meta.url).href },
  { key: 'factory_war', src: new URL('../../assets/cards/工厂/战争.png', import.meta.url).href },
  { key: 'factory_longriver', src: new URL('../../assets/cards/工厂/长江.png', import.meta.url).href },
  { key: 'factory_bamboo', src: new URL('../../assets/cards/工厂/竹.png', import.meta.url).href },
  { key: 'factory_zhuangzhinanchou', src: new URL('../../assets/cards/工厂/壮志难酬.png', import.meta.url).href },
  { key: 'factory_nature', src: new URL('../../assets/cards/工厂/自然.png', import.meta.url).href },

  { key: 'jiangjinjiu', src: new URL('../../assets/cards/诗词/将进酒.png', import.meta.url).href },
  { key: 'shudaonan', src: new URL('../../assets/cards/诗词/蜀道难.png', import.meta.url).href },
  { key: 'xinglunan', src: new URL('../../assets/cards/诗词/行路难.png', import.meta.url).href },
  { key: 'huanghelousongmenghaoranzhiguangling', src: new URL('../../assets/cards/诗词/黄鹤楼送孟浩然之广陵.png', import.meta.url).href },
  { key: 'jingyesi', src: new URL('../../assets/cards/诗词/静夜思.png', import.meta.url).href },
  { key: 'wanglushanpubu', src: new URL('../../assets/cards/诗词/望庐山瀑布.png', import.meta.url).href },
  { key: 'zengwanglun', src: new URL('../../assets/cards/诗词/赠汪伦.png', import.meta.url).href },
  { key: 'wenwangchanglingzuoqianlongbiaoyaoyouciji', src: new URL('../../assets/cards/诗词/闻王昌龄左迁龙标遥有此寄.png', import.meta.url).href },
  { key: 'emeishanyuege', src: new URL('../../assets/cards/诗词/峨眉山月歌.png', import.meta.url).href },
  { key: 'shizhisaishang', src: new URL('../../assets/cards/诗词/使至塞上.png', import.meta.url).href },
  { key: 'xiangsi', src: new URL('../../assets/cards/诗词/相思.png', import.meta.url).href },
  { key: 'songyuanershianxi', src: new URL('../../assets/cards/诗词/送元二使安西.png', import.meta.url).href },
  { key: 'jiuyuejiuriyishandongxiongdi', src: new URL('../../assets/cards/诗词/九月九日忆山东兄弟.png', import.meta.url).href },
  { key: 'weichengqu', src: new URL('../../assets/cards/诗词/渭城曲.png', import.meta.url).href },
  { key: 'shanjuqiuming', src: new URL('../../assets/cards/诗词/山居秋暝.png', import.meta.url).href },
  { key: 'niaomingjian', src: new URL('../../assets/cards/诗词/鸟鸣涧.png', import.meta.url).href },
  { key: 'zhuliguan', src: new URL('../../assets/cards/诗词/竹里馆.png', import.meta.url).href },
  { key: 'shuidiaogetou_mingyuejishiyou', src: new URL('../../assets/cards/诗词/水调歌头·明月几时有.png', import.meta.url).href },
  { key: 'chibifu', src: new URL('../../assets/cards/诗词/赤壁赋.png', import.meta.url).href },
  { key: 'jichengtansiyeyou', src: new URL('../../assets/cards/诗词/记承天寺夜游.png', import.meta.url).href },
  { key: 'tixilinbi', src: new URL('../../assets/cards/诗词/题西林壁.png', import.meta.url).href },
  { key: 'yinshangchuqinghouyu', src: new URL('../../assets/cards/诗词/饮湖上初晴后雨.png', import.meta.url).href },
  { key: 'dingfengbo_motingchuanlindayesheng', src: new URL('../../assets/cards/诗词/定风波·莫听穿林打叶声.png', import.meta.url).href },
  { key: 'busuanzi_huangzhoudinghuiyuanyujuzuo', src: new URL('../../assets/cards/诗词/卜算子·黄州定慧院寓居作.png', import.meta.url).href },
  { key: 'denggao', src: new URL('../../assets/cards/诗词/登高.png', import.meta.url).href },
  { key: 'maowuweiqiufengsuopoerge', src: new URL('../../assets/cards/诗词/茅屋为秋风所破歌.png', import.meta.url).href },
  { key: 'chunyexiyu', src: new URL('../../assets/cards/诗词/春夜喜雨.png', import.meta.url).href },
  { key: 'wangyue', src: new URL('../../assets/cards/诗词/望岳.png', import.meta.url).href },
  { key: 'wenguanjushouhenanhubei', src: new URL('../../assets/cards/诗词/闻官军收河南河北.png', import.meta.url).href },
  { key: 'chunwang', src: new URL('../../assets/cards/诗词/春望.png', import.meta.url).href },
  { key: 'jueju_lianggehuanglimingcuiliu', src: new URL('../../assets/cards/诗词/绝句·两个黄鹂鸣翠柳.png', import.meta.url).href },
  { key: 'bochuanguazhou', src: new URL('../../assets/cards/诗词/泊船瓜洲.png', import.meta.url).href },
  { key: 'dengfeilaifeng', src: new URL('../../assets/cards/诗词/登飞来峰.png', import.meta.url).href },
  { key: 'yuanri', src: new URL('../../assets/cards/诗词/元日.png', import.meta.url).href },
  { key: 'pozhenzi_weichentongfuzhuangciziyijizhi', src: new URL('../../assets/cards/诗词/破阵子·为陈同甫赋壮词以寄之.png', import.meta.url).href },
  { key: 'xijiangyue_yexinghuangshadaozhong', src: new URL('../../assets/cards/诗词/西江月·夜行黄沙道中.png', import.meta.url).href },
  { key: 'chounuer_shuboshandaozhongbi', src: new URL('../../assets/cards/诗词/丑奴儿·书博山道中壁.png', import.meta.url).href },
  { key: 'guiqulaixici', src: new URL('../../assets/cards/诗词/归去来兮辞.png', import.meta.url).href },
  { key: 'taohuayuanji', src: new URL('../../assets/cards/诗词/桃花源记.png', import.meta.url).href },
  { key: 'yinjian_jieluzairenjing', src: new URL('../../assets/cards/诗词/饮酒·结庐在人境.png', import.meta.url).href },
  { key: 'changhenge', src: new URL('../../assets/cards/诗词/长恨歌.png', import.meta.url).href },
  { key: 'qiantanghuchunxing', src: new URL('../../assets/cards/诗词/钱塘湖春行.png', import.meta.url).href },
  { key: 'fudeguyuancaosongbie', src: new URL('../../assets/cards/诗词/赋得古原草送别.png', import.meta.url).href },
  { key: 'yijiangnan', src: new URL('../../assets/cards/诗词/忆江南.png', import.meta.url).href },
  { key: 'pipaxing', src: new URL('../../assets/cards/诗词/琵琶行.png', import.meta.url).href },
  { key: 'dalinsitaohua', src: new URL('../../assets/cards/诗词/大林寺桃花.png', import.meta.url).href },
  { key: 'loushiming', src: new URL('../../assets/cards/诗词/陋室铭.png', import.meta.url).href },
  { key: 'chouletianyanzhouchufengxishangjianzheng', src: new URL('../../assets/cards/诗词/酬乐天扬州初逢席上见赠.png', import.meta.url).href },
  { key: 'wangdongting', src: new URL('../../assets/cards/诗词/望洞庭.png', import.meta.url).href },
  { key: 'youshanxicun', src: new URL('../../assets/cards/诗词/游山西村.png', import.meta.url).href },
  { key: 'chaitoufeng_hongsushou', src: new URL('../../assets/cards/诗词/钗头凤·红酥手.png', import.meta.url).href },
  { key: 'jinse', src: new URL('../../assets/cards/诗词/锦瑟.png', import.meta.url).href },
  { key: 'wuti_xiangjianshinnanbieyinan', src: new URL('../../assets/cards/诗词/无题 相见时难别亦难.png', import.meta.url).href },
  { key: 'yeyujibei', src: new URL('../../assets/cards/诗词/夜雨寄北.png', import.meta.url).href },
  { key: 'jiasheng', src: new URL('../../assets/cards/诗词/贾生.png', import.meta.url).href },
  //{ key: 'wanxisha_yiquxincijiuyibei', src: new URL('../../assets/cards/诗词/浣溪沙·一曲新词酒一杯.png', import.meta.url).href }
  { key: 'wanxisha_yiquxincijiuyibei', src: new URL('../../assets/cards/诗词/浣溪沙·一曲新词酒一杯.png', import.meta.url).href }
]

// 配方映射
export const recipeMapping = {
  autumn_bird: 'goose',
  bird_bird: 'friend',
  fire_fire: 'war',
  fire_moon: 'sun',
  friend_missing: 'love',
  home_byebye: 'missing',
  mountain_water: 'nature',
  nature_spring: 'flower',
  nature_water: 'bamboo',
  rain_rain: 'yellowriver',
  spring_water: 'liu',
  bamboo_water: 'danbo',
  fire_water: 'wine',
  water_water: 'rain',
  autumn_wine: 'zhuangzhinanchou',
  water_yellowriver: 'longriver',
  moon_moon: 'home',
  home_moon: 'byebye',
  autumn_autumn: 'sad'
}

export const craftingRecipes = {
  bird_libai_mountain: 'shudaonan',
  autumn_friend_libai: 'emeishanyuege',
  byebye_friend_libai: 'zengwanglun',
  friend_libai_moon: 'wenwangchanglingzuoqianlongbiaoyaoyouciji',
  home_libai_moon: 'jingyesi',
  byebye_libai_longriver: 'huanghelousongmenghaoranzhiguangling',
  libai_mountain_water: 'wanglushanpubu',
  autumn_libai_wine: 'xinglunan',
  libai_wine_yellowriver: 'jiangjinjiu',

  autumn_dufu_rain: 'maowuweiqiufengsuopoerge',
  bird_dufu_liu: 'jueju_lianggehuanglimingcuiliu',
  bird_dufu_mountain: 'wangyue',
  dufu_home_war: 'wenguanjushouhenanhubei',
  dufu_rain_spring: 'chunyexiyu',
  dufu_spring_war: 'chunwang',
  autumn_dufu_zhuangzhinanchou: 'denggao',

  goose_wangwei_yellowriver: 'shizhisaishang',
  friend_wangwei_wine: 'songyuanershianxi',
  spring_missing_wangwei: 'xiangsi',
  home_missing_wangwei: 'jiuyuejiuriyishandongxiongdi',
  byebye_friend_wangwei: 'weichengqu',
  autumn_rain_wangwei: 'shanjuqiuming',
  bamboo_danbo_wangwei: 'zhuliguan',
  bird_moon_wangwei: 'niaomingjian',

  moon_sushi_water: 'shuidiaogetou_mingyuejishiyou',
  fire_mountain_sushi: 'chibifu',
  moon_sushi_zhuangzhinanchou: 'jichengtansiyeyou',
  mountain_mountain_sushi: 'tixilinbi',
  rain_sushi_water: 'yinshangchuqinghouyu',
  bamboo_rain_sushi: 'dingfengbo_motingchuanlindayesheng',
  goose_moon_sushi: 'busuanzi_huangzhoudinghuiyuanyujuzuo',

  longriver_spring_wanganshi: 'bochuanguazhou',
  mountain_sun_wanganshi: 'dengfeilaifeng',
  spring_spring_wanganshi: 'yuanri',

  autumn_sad_xinqiji: 'chounuer_shuboshandaozhongbi',
  moon_nature_xinqiji: 'xijiangyue_yexinghuangshadaozhong',
  war_xinqiji_zhuangzhinanchou: 'pozhenzi_weichentongfuzhuangciziyijizhi',

  nature_nature_taoyuanming: 'guiqulaixici',
  flower_nature_taoyuanming: 'taohuayuanji',
  nature_taoyuanming_wine: 'yinjian_jieluzairenjing',

  baijuyi_love_sad: 'changhenge',
  baijuyi_spring_water: 'qiantanghuchunxing',
  baijuyi_byebye_spring: 'fudeguyuancaosongbie',
  baijuyi_longriver_spring: 'yijiangnan',
  baijuyi_byebye_sad: 'pipaxing',
  baijuyi_flower_spring: 'dalinsitaohua',

  danbo_liuyuxi_nature: 'loushiming',
  home_liuyuxi_sad: 'chouletianyanzhouchufengxishangjianzheng',
  liuyuxi_mountain_water: 'wangdongting',

  luyou_nature_wine: 'youshanxicun',
  love_luyou_sad: 'chaitoufeng_hongsushou',

  lishangyin_love_sad: 'jinse',
  byebye_lishangyin_love: 'wuti_xiangjianshinnanbieyinan',
  lishangyin_missing_rain: 'yeyujibei',
  lishangyin_zhuangzhinanchou_zhuangzhinanchou: 'jiasheng',

  spring_wine_yanshu: 'wanxisha_yiquxincijiuyibei',

  // 工厂配方
  autumn_autumn_factory: 'factory_autumn',
  bamboo_bamboo_factory: 'factory_bamboo',
  bird_bird_factory: 'factory_bird',
  byebye_byebye_factory: 'factory_byebye',
  danbo_danbo_factory: 'factory_danbo',
  factory_fire_fire: 'factory_fire',
  factory_flower_flower: 'factory_flower',
  factory_friend_friend: 'factory_friend',
  factory_goose_goose: 'factory_goose',
  factory_home_home: 'factory_home',
  factory_liu_liu: 'factory_liu',
  factory_longriver_longriver: 'factory_longriver',
  factory_love_love: 'factory_love',
  factory_missing_missing: 'factory_missing',
  factory_moon_moon: 'factory_moon',
  factory_mountain_mountain: 'factory_mountain',
  factory_nature_nature: 'factory_nature',
  factory_rain_rain: 'factory_rain',
  factory_sad_sad: 'factory_sad',
  factory_spring_spring: 'factory_spring',
  factory_sun_sun: 'factory_sun',
  factory_war_war: 'factory_war',
  factory_water_water: 'factory_water',
  factory_wine_wine: 'factory_wine',
  factory_yellowriver_yellowriver: 'factory_yellowriver',
  factory_zhuangzhinanchou_zhuangzhinanchou: 'factory_zhuangzhinanchou'
}

export const cardPrices = {
  card_pack_poem: 10,
  card_pack_poet: 10,
  card_worker: 1,
  factory: 10,
  love: 7,
  sad: 2,
  spring: 1,
  danbo: 4,
  home: 2,
  yellowriver: 4,
  fire: 1,
  wine: 2,
  byebye: 3,
  liu: 2,
  bird: 1,
  autumn: 1,
  sun: 2,
  mountain: 1,
  water: 1,
  missing: 5,
  flower: 3,
  goose: 2,
  friend: 2,
  rain: 2,
  moon: 1,
  war: 2,
  longriver: 5,
  bamboo: 3,
  zhuangzhinanchou: 3,
  nature: 2,
  baijuyi: 2,
  dufu: 2,
  libai: 1,
  lishangyin: 2,
  liuyuxi: 3,
  luyou: 3,
  sushi: 2,
  taoyuanming: 3,
  wanganshi: 3,
  wangwei: 1,
  xinqiji: 4,
  yanshu: 4,
  factory_love: 10,
  factory_sad: 10,
  factory_spring: 10,
  factory_danbo: 10,
  factory_home: 10,
  factory_yellowriver: 10,
  factory_fire: 10,
  factory_wine: 10,
  factory_byebye: 10,
  factory_liu: 10,
  factory_bird: 10,
  factory_autumn: 10,
  factory_sun: 10,
  factory_mountain: 10,
  factory_water: 10,
  factory_missing: 10,
  factory_flower: 10,
  factory_goose: 10,
  factory_friend: 10,
  factory_rain: 10,
  factory_moon: 10,
  factory_war: 10,
  factory_longriver: 10,
  factory_bamboo: 10,
  factory_zhuangzhinanchou: 10,
  factory_nature: 10,
  jiangjinjiu: 10,
  shudaonan: 10,
  xinglunan: 10,
  huanghelousongmenghaoranzhiguangling: 10,
  jingyesi: 10,
  wanglushanpubu: 10,
  zengwanglun: 10,
  wenwangchanglingzuoqianlongbiaoyaoyouciji: 10,
  emeishanyuege: 10,
  shizhisaishang: 10,
  xiangsi: 10,
  songyuanershianxi: 10,
  jiuyuejiuriyishandongxiongdi: 10,
  weichengqu: 10,
  shanjuqiuming: 10,
  niaomingjian: 10,
  zhuliguan: 10,
  shuidiaogetou_mingyuejishiyou: 10,
  chibifu: 10,
  jichengtansiyeyou: 10,
  tixilinbi: 10,
  yinshangchuqinghouyu: 10,
  dingfengbo_motingchuanlindayesheng: 10,
  busuanzi_huangzhoudinghuiyuanyujuzuo: 10,
  denggao: 10,
  maowuweiqiufengsuopoerge: 10,
  chunyexiyu: 10,
  wangyue: 10,
  wenguanjushouhenanhubei: 10,
  chunwang: 10,
  jueju_lianggehuanglimingcuiliu: 10,
  bochuanguazhou: 10,
  dengfeilaifeng: 10,
  yuanri: 10,
  pozhenzi_weichentongfuzhuangciziyijizhi: 10,
  xijiangyue_yexinghuangshadaozhong: 10,
  chounuer_shuboshandaozhongbi: 10,
  guiqulaixici: 10,
  taohuayuanji: 10,
  yinjian_jieluzairenjing: 10,
  changhenge: 10,
  qiantanghuchunxing: 10,
  fudeguyuancaosongbie: 10,
  yijiangnan: 10,
  pipaxing: 10,
  dalinsitaohua: 10,
  loushiming: 10,
  chouletianyanzhouchufengxishangjianzheng: 10,
  wangdongting: 10,
  youshanxicun: 10,
  chaitoufeng_hongsushou: 10,
  jinse: 10,
  wuti_xiangjianshinnanbieyinan: 10,
  yeyujibei: 10,
  jiasheng: 10,
  wanxisha_yiquxincijiuyibei: 10
}

// 合成表数据
export const recipes = ref([])

export function initializeRecipes() {
  const allRecipeEntries = Object.entries(recipeMapping)
  recipes.value = allRecipeEntries.map(([recipeKey, resultType], index) => ({
    id: index + 1,
    recipeKey,
    resultType,
    card1: { src: getCardImageSrc('unknown_card') },
    card2: { src: getCardImageSrc('unknown_card') },
    result: { src: getCardImageSrc('unknown_card') },
    unlocked: false
  }))
}

export function getCardImageSrc(cardType) {
  const cardImage = cardImages.find(img => img.key === cardType)
  return cardImage ? cardImage.src : new URL('../../assets/cards/未知卡片.png', import.meta.url).href
}

export function checkRecipe(card1Type, card2Type) {
  const types = [card1Type, card2Type].sort()
  const recipeKey = types.join('_')
  return recipeMapping[recipeKey]
}

export function checkCrafting(cards) {
  if (cards.length !== 3) return null
  const types = cards.map(card => card.getData('type')).sort()
  const recipeKey = types.join('_')
  return craftingRecipes[recipeKey]
}